name = "CTFlows"
uuid = "1c39547c-7794-42f7-af83-d98194f657c2"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]
version = "0.1.0"

[deps]
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
CTBase = "0.4"
OrdinaryDiffEq = "6.44"
julia = "1.8"